/* Date: 17-May-17 : Methods in the class have been commented by Nirvana Team to resolve merge issues for Edge R2a Sprint 17.0.1 TCM Integration functionality */ 
//public class ManageCustomerUpdateHandler extends IntegrationQueueHandler {
public class ManageCustomerUpdateHandler{

	public ManageCustomerUpdateHandler() {
	/*
		super(ManageCustomerUpdateHandler.class.getName());
		*/
	}

	/*
	*	The params will be a list of account Ids that needs to be updated in TCM
	*/
	/*
	public override void executeWork(List<String> params) {
		ManageCustomerManager.enqueueUpdate(ManageCustomerUpdateHandler.class.getName(), params);
	}*/
}